export const SHIPMENT_ACTIONS = {
    FETCH_SHIPMENTS_START: "FETCH_SHIPMENTS_START",
    FETCH_SHIPMENTS_SUCCESS: "FETCH_SHIPMENTS_SUCCESS",
    FETCH_SHIPMENTS_FAILURE: "FETCH_SHIPMENTS_FAILURE",

    EDIT_NAME_START: "EDIT_NAME_START",
    EDIT_NAME_SUCCESS: "EDIT_NAME_SUCCESS",
    EDIT_NAME_FAILURE: "EDIT_NAME_FAILURE",
};